# 命名空间 流水线指定
#apiVersion: v1
#kind: Namespace
#metadata:
#   name: gmall-dev

# Deployment 部署
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: trade-center-dev
  name: trade-center-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      run: trade-center-dev
  template:
    metadata:
      labels:
        run: trade-center-dev
    spec:
      containers:
        - image: ${IMAGE}
          name: app
          resources:
            requests:
              memory: 1124Mi
            limits:
              memory: 1124Mi
          imagePullPolicy: Always
      imagePullSecrets:
        - name: aliyun-priv-regcred

---

# Service 部署
apiVersion: v1
kind: Service
metadata:
  name: trade-center-dev
  labels:
    test: test
    labele2: label
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    run: trade-center-dev
  sessionAffinity: None
  type: ClusterIP

---

# Ingress 部署
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trade-center-dev
spec:
  ingressClassName: nginx
  rules:
    - host: trade-center-dev.${HOST}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trade-center-dev
                port:
                  number: 8080
